# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be2039aac26d0fd03381a69a7cb2b7088509393a1c9e0404521855d02e3c5733ae3fa4b6cd016d72509e5bd34ffaa1f5cfe1800f980339517b58ccb3397bc98c

test:
  secret_key_base: 919e6f4dfce5bfd3c8ef5569440ea20acf35ffad2cd3335d274f0b6ab1304981dc089b5d11cb76386f9be54c2b15f48da5276651c5df91527c5a4035648a28de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
